# Basic configurations on Lebedev dataset


# Data
dataset: Lebedev
num_workers: 2
repeats: 7
subset: val
crop_size: 192


# Optimizer
optimizer: Adam
lr: 0.001
weight_decay: 0.0
load_optim: False
save_optim: False
sched_on: True
schedulers:
  - name: StepLR
    step_size: 20
    gamma: 0.5


# Training related
batch_size: 8
num_epochs: 80
resume: ''
anew: False
device: cuda


# Experiment
exp_dir: ../exp/
# tag: ''
# suffix: ''
# DO NOT specify exp_config
debug_on: False
inherit_off: False
log_off: False
track_intvl: 10
tb_on: False
tb_intvl: 15
suffix_off: False
save_on: False
out_dir:


# Criterion
criterion: WNLL
weights: 
  - 0.1   # Weight of no-change class
  - 0.9   # Weight of change class


# Model
model: 